@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjNDNjZCRjIzMjBGNkY4RDQ2QzJERDhCMjI0MEVGMTFENTZEQkY3MUYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJQR2FfSXlEMi1OUnNMZGl5SkE3eEhWYmI5eDgifQ.eyJuYmYiOjE3NzE2MDM0NTEsImV4cCI6MTc3MTYwNzA1MSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmVtc2ljbG91ZC5jb20iLCJhdWQiOlsiZW1zaV9vcGVuIiwiaHR0cHM6Ly9hdXRoLmVtc2ljbG91ZC5jb20vcmVzb3VyY2VzIl0sImNsaWVudF9pZCI6Im1ydHpkOWgzcTJybXMyNG0iLCJuYW1lIjoiTW9oYW1hZCBBbHpob3JpIiwiY29tcGFueSI6Iklnbml6aWEiLCJlbWFpbCI6Im1hbHpob3JpQGlnbml6aWEuYWkiLCJpYXQiOjE3NzE2MDM0NTEsInNjb3BlIjpbImVtc2lfb3BlbiJdfQ.Q2X6Le70E_50TQYsljwulm8mT5K6ALW8sGdVBjo3ZqjONXL3JyC7CVupSeiM2rXvz-jjaOlzgr1oNtbn8_uRHesCNN1jcNJqnXA2CQfROG1Qqk9iQ-WBfJRSgmyw82krpGfNJY7YzFjq274bkOEkVu-OFlNZXXM6XbP6VgNBIPu7XBUsViBJroj9JFAeCXw5j2pfVbAzG7zpCQKwGGANdl5H8KKqz3eaTyI-cGxUTpnS_VkIOS_ow9nTTMIgS6VMSKjeL-m8Uw-nKDh4iSRCjgLJ-E_-Z98esClscVW5oZIAR8Tp7f4IIBVA-TO24LUOBJkTNKujsslu3Ji_Jf50Wg

GET https://emsiservices.com/skills/versions/latest/skills?q=collaboration&typeIds=ST1,ST2&fields=id,name,type,infoUrl
Authorization: Bearer {{token}}